// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(modelpipe_ffiFFI)
import modelpipe_ffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_modelpipe_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_modelpipe_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }

    init(rawBufferPointer: UnsafeRawBufferPointer) {
        self.init(
            len: Int32(rawBufferPointer.count),
            data: rawBufferPointer.baseAddress?.assumingMemoryBound(to: UInt8.self)
        )
    }
}

// Converter for `&[u8]` / `[ByRef] bytes` arguments.
//
// Conforms to `FfiConverter` so the compiler enforces the full converter
// method set. Only the scope-bound `lower(_:_body:)` overload is sound —
// zero-copy byte buffers only flow foreign -> Rust, and only in argument
// position. The four protocol-witness methods (`lift`, `lower`, `read`,
// `write`) `fatalError` at runtime if anyone reaches them.
//
// The scope-bound `lower` takes a closure because the `ForeignBytes`
// pointer is only guaranteed valid for the duration of
// `Data.withUnsafeBytes`. Callers must run the full FFI call inside
// the closure body.
fileprivate enum FfiConverterByRefBytes: FfiConverter {
    typealias SwiftType = Data
    typealias FfiType = ForeignBytes

    static func lower<R>(_ value: Data, _ body: (ForeignBytes) throws -> R) rethrows -> R {
        return try value.withUnsafeBytes { rawBuf in
            try body(ForeignBytes(rawBufferPointer: rawBuf))
        }
    }

    static func lower(_ value: Data) -> ForeignBytes {
        fatalError("ByRef bytes cannot use the plain lower: returning ForeignBytes escapes the Data.withUnsafeBytes scope. Use the scope-bound lower(_:_body:) overload instead.")
    }

    static func lift(_ value: ForeignBytes) throws -> Data {
        fatalError("ByRef bytes cannot be lifted: zero-copy &[u8] only flows foreign->Rust")
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        fatalError("ByRef bytes cannot be read from a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }

    static func write(_ value: Data, into buf: inout [UInt8]) {
        fatalError("ByRef bytes cannot be written to a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureModelpipeFfiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt16: FfiConverterPrimitive {
    typealias FfiType = UInt16
    typealias SwiftType = UInt16

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt16 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        // Use Swift's native UTF-8 decoder; `String(bytes:encoding:.utf8)` goes
        // through Foundation's NSString and silently strips a leading U+FEFF BOM.
        // Invalid UTF-8 substitutes U+FFFD instead of trapping (unreachable
        // given Rust's `String` invariant).
        return String(decoding: bytes, as: UTF8.self)
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        // See `lift` above for why we avoid Foundation's NSString-backed decoder here.
        return String(decoding: try readBytes(&buf, count: Int(len)), as: UTF8.self)
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




/**
 * A live pipe: a loopback listener on this device that *is* the far
 * machine's model server.
 *
 * Held by Swift as a reference-counted object. Dropping the last reference
 * tears the pipe down, so an app that loses its last reference without
 * calling [`Self::shutdown`] still leaves nothing bound — but call it anyway,
 * because only that path tells the far side rather than leaving it to time
 * out.
 */
public protocol MpPipeProtocol: AnyObject, Sendable {
    
    /**
     * `http://127.0.0.1:<port>/v1` — point an OpenAI-compatible client here,
     * with the far machine's key as the API key.
     *
     * Stable for the life of the pipe.
     */
    func baseUrl()  -> String
    
    /**
     * Why the pipe closed, or `None` while it is open.
     */
    func closeReason()  -> MpCloseReason?
    
    /**
     * Transport counters for this pipe's endpoint.
     */
    func networkMetrics()  -> MpNetworkMetrics
    
    /**
     * Tell the endpoint the network underneath it may have changed.
     *
     * Call this from the app's own foreground/resume handling, every time,
     * without trying to work out whether it was needed. It is harmless when
     * nothing changed and harmless when the endpoint already noticed.
     *
     * It exists because iOS is one of the hosts iroh cannot watch for itself:
     * sleep/wake detection there is deliberately disabled in favour of a poll
     * measured in the hour, so a phone that resumes on a new cellular bearer
     * has a pipe with nothing to repair it until that poll comes round —
     * unless the app says so, here, from the resume it already handles.
     */
    func notifyNetworkChange() async 
    
    /**
     * The loopback port this pipe bound.
     *
     * [`Self::base_url`] is what a client wants; this is for a log line or a
     * diagnostic screen that wants the number on its own.
     */
    func port()  -> UInt16
    
    /**
     * Close the pipe, telling the far side rather than leaving it to time
     * out.
     *
     * Idempotent: calling it twice is fine, and the second call returns at
     * once. Afterwards the base URL refuses connections rather than hanging,
     * and the status sequence has ended.
     */
    func shutdown() async 
    
    /**
     * What the pipe is doing right now.
     */
    func status()  -> MpPipeStatus
    
    /**
     * Wait for a status different from `snapshot`, then return it; `None`
     * once the pipe is closed and `snapshot` already says so.
     *
     * The caller supplies the snapshot, which is the whole point: a
     * transition landing between reading [`Self::status`] and waiting again
     * is reported rather than coalesced away, and the sequence *ends* instead
     * of answering `Closed` forever at whatever rate it is asked.
     *
     * The Swift shape this is for:
     *
     * ```swift
     * var held = pipe.status()
     * continuation.yield(held)                       // current value first
     * while let next = await pipe.statusChangedSince(snapshot: held) {
     * held = next
     * continuation.yield(held)
     * }
     * continuation.finish()                          // only after a close
     * ```
     */
    func statusChangedSince(snapshot: MpPipeStatus) async  -> MpPipeStatus?
    
}
/**
 * A live pipe: a loopback listener on this device that *is* the far
 * machine's model server.
 *
 * Held by Swift as a reference-counted object. Dropping the last reference
 * tears the pipe down, so an app that loses its last reference without
 * calling [`Self::shutdown`] still leaves nothing bound — but call it anyway,
 * because only that path tells the far side rather than leaving it to time
 * out.
 */
open class MpPipe: MpPipeProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_modelpipe_ffi_fn_clone_mppipe(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_modelpipe_ffi_fn_free_mppipe(handle, $0) }
    }

    

    
    /**
     * `http://127.0.0.1:<port>/v1` — point an OpenAI-compatible client here,
     * with the far machine's key as the API key.
     *
     * Stable for the life of the pipe.
     */
open func baseUrl() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_modelpipe_ffi_fn_method_mppipe_base_url(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
    /**
     * Why the pipe closed, or `None` while it is open.
     */
open func closeReason() -> MpCloseReason?  {
    return try!  FfiConverterOptionTypeMpCloseReason.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_modelpipe_ffi_fn_method_mppipe_close_reason(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
    /**
     * Transport counters for this pipe's endpoint.
     */
open func networkMetrics() -> MpNetworkMetrics  {
    return try!  FfiConverterTypeMpNetworkMetrics_lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_modelpipe_ffi_fn_method_mppipe_network_metrics(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
    /**
     * Tell the endpoint the network underneath it may have changed.
     *
     * Call this from the app's own foreground/resume handling, every time,
     * without trying to work out whether it was needed. It is harmless when
     * nothing changed and harmless when the endpoint already noticed.
     *
     * It exists because iOS is one of the hosts iroh cannot watch for itself:
     * sleep/wake detection there is deliberately disabled in favour of a poll
     * measured in the hour, so a phone that resumes on a new cellular bearer
     * has a pipe with nothing to repair it until that poll comes round —
     * unless the app says so, here, from the resume it already handles.
     */
open func notifyNetworkChange()async   {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_modelpipe_ffi_fn_method_mppipe_notify_network_change(
                        self.uniffiCloneHandle()
                )
            },
            pollFunc: ffi_modelpipe_ffi_rust_future_poll_void,
            completeFunc: ffi_modelpipe_ffi_rust_future_complete_void,
            freeFunc: ffi_modelpipe_ffi_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: nil
            
        )
}
    
    /**
     * The loopback port this pipe bound.
     *
     * [`Self::base_url`] is what a client wants; this is for a log line or a
     * diagnostic screen that wants the number on its own.
     */
open func port() -> UInt16  {
    return try!  FfiConverterUInt16.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_modelpipe_ffi_fn_method_mppipe_port(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
    /**
     * Close the pipe, telling the far side rather than leaving it to time
     * out.
     *
     * Idempotent: calling it twice is fine, and the second call returns at
     * once. Afterwards the base URL refuses connections rather than hanging,
     * and the status sequence has ended.
     */
open func shutdown()async   {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_modelpipe_ffi_fn_method_mppipe_shutdown(
                        self.uniffiCloneHandle()
                )
            },
            pollFunc: ffi_modelpipe_ffi_rust_future_poll_void,
            completeFunc: ffi_modelpipe_ffi_rust_future_complete_void,
            freeFunc: ffi_modelpipe_ffi_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: nil
            
        )
}
    
    /**
     * What the pipe is doing right now.
     */
open func status() -> MpPipeStatus  {
    return try!  FfiConverterTypeMpPipeStatus_lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_modelpipe_ffi_fn_method_mppipe_status(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
    /**
     * Wait for a status different from `snapshot`, then return it; `None`
     * once the pipe is closed and `snapshot` already says so.
     *
     * The caller supplies the snapshot, which is the whole point: a
     * transition landing between reading [`Self::status`] and waiting again
     * is reported rather than coalesced away, and the sequence *ends* instead
     * of answering `Closed` forever at whatever rate it is asked.
     *
     * The Swift shape this is for:
     *
     * ```swift
     * var held = pipe.status()
     * continuation.yield(held)                       // current value first
     * while let next = await pipe.statusChangedSince(snapshot: held) {
     * held = next
     * continuation.yield(held)
     * }
     * continuation.finish()                          // only after a close
     * ```
     */
open func statusChangedSince(snapshot: MpPipeStatus)async  -> MpPipeStatus?  {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_modelpipe_ffi_fn_method_mppipe_status_changed_since(
                        self.uniffiCloneHandle(),FfiConverterTypeMpPipeStatus_lower(snapshot)
                )
            },
            pollFunc: ffi_modelpipe_ffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_modelpipe_ffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_modelpipe_ffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterOptionTypeMpPipeStatus.lift,
            errorHandler: nil
            
        )
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMpPipe: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = MpPipe

    public static func lift(_ handle: UInt64) throws -> MpPipe {
        return MpPipe(unsafeFromHandle: handle)
    }

    public static func lower(_ value: MpPipe) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MpPipe {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: MpPipe, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMpPipe_lift(_ handle: UInt64) throws -> MpPipe {
    return try FfiConverterTypeMpPipe.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMpPipe_lower(_ value: MpPipe) -> UInt64 {
    return FfiConverterTypeMpPipe.lower(value)
}




/**
 * Options for a dial. `MpConnectOptions::default()` is the right answer
 * almost always.
 */
public struct MpConnectOptions: Equatable, Hashable {
    /**
     * Bind this loopback port instead of letting the OS pick a free one.
     *
     * Leave it `None`. A fixed port is for reproducing a bug, and on a phone
     * it is a way to fail a dial that would otherwise have worked.
     */
    public var port: UInt16?
    /**
     * Use this relay instead of the public ones.
     */
    public var relayUrl: String?
    /**
     * Ask the router to map a port (UPnP/NAT-PMP/PCP).
     *
     * On by default, as upstream. Harmless where the router says no.
     */
    public var portMapping: Bool
    /**
     * Publish to, and resolve through, n0's discovery service.
     *
     * On by default. Turning it off restricts the dial to the addresses the
     * ticket was minted with, which for a machine that has since changed
     * network means no dial at all.
     */
    public var discovery: Bool
    /**
     * Skip hole punching and go through a relay from the start.
     *
     * Off by default. Useful only for making the relay path reproducible,
     * which is otherwise hard to force.
     */
    public var relayOnly: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Bind this loopback port instead of letting the OS pick a free one.
         *
         * Leave it `None`. A fixed port is for reproducing a bug, and on a phone
         * it is a way to fail a dial that would otherwise have worked.
         */port: UInt16? = nil, 
        /**
         * Use this relay instead of the public ones.
         */relayUrl: String? = nil, 
        /**
         * Ask the router to map a port (UPnP/NAT-PMP/PCP).
         *
         * On by default, as upstream. Harmless where the router says no.
         */portMapping: Bool = true, 
        /**
         * Publish to, and resolve through, n0's discovery service.
         *
         * On by default. Turning it off restricts the dial to the addresses the
         * ticket was minted with, which for a machine that has since changed
         * network means no dial at all.
         */discovery: Bool = true, 
        /**
         * Skip hole punching and go through a relay from the start.
         *
         * Off by default. Useful only for making the relay path reproducible,
         * which is otherwise hard to force.
         */relayOnly: Bool = false) {
        self.port = port
        self.relayUrl = relayUrl
        self.portMapping = portMapping
        self.discovery = discovery
        self.relayOnly = relayOnly
    }

    

    
}

#if compiler(>=6)
extension MpConnectOptions: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMpConnectOptions: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MpConnectOptions {
        return
            try MpConnectOptions(
                port: FfiConverterOptionUInt16.read(from: &buf), 
                relayUrl: FfiConverterOptionString.read(from: &buf), 
                portMapping: FfiConverterBool.read(from: &buf), 
                discovery: FfiConverterBool.read(from: &buf), 
                relayOnly: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: MpConnectOptions, into buf: inout [UInt8]) {
        FfiConverterOptionUInt16.write(value.port, into: &buf)
        FfiConverterOptionString.write(value.relayUrl, into: &buf)
        FfiConverterBool.write(value.portMapping, into: &buf)
        FfiConverterBool.write(value.discovery, into: &buf)
        FfiConverterBool.write(value.relayOnly, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMpConnectOptions_lift(_ buf: RustBuffer) throws -> MpConnectOptions {
    return try FfiConverterTypeMpConnectOptions.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMpConnectOptions_lower(_ value: MpConnectOptions) -> RustBuffer {
    return FfiConverterTypeMpConnectOptions.lower(value)
}


/**
 * What the transport underneath this pipe has been doing, since it started.
 *
 * Monotonic totals for one endpoint's whole life, so the reading that means
 * something is a difference or a ratio rather than any single number. The
 * rate-limit counter is the one nothing else on the phone can see: a relay
 * refusing this endpoint looks exactly like a network that will not connect.
 */
public struct MpNetworkMetrics: Equatable, Hashable {
    /**
     * Relay connections this endpoint has opened.
     */
    public var relayConnections: UInt64
    /**
     * Relay connections that failed to open.
     */
    public var relayConnectionsFailed: UInt64
    /**
     * Relay connections refused because the relay is rate limiting this
     * endpoint. Non-zero here is the difference between "the network is
     * broken" and "this endpoint is being throttled".
     */
    public var relayConnectionsRatelimited: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Relay connections this endpoint has opened.
         */relayConnections: UInt64, 
        /**
         * Relay connections that failed to open.
         */relayConnectionsFailed: UInt64, 
        /**
         * Relay connections refused because the relay is rate limiting this
         * endpoint. Non-zero here is the difference between "the network is
         * broken" and "this endpoint is being throttled".
         */relayConnectionsRatelimited: UInt64) {
        self.relayConnections = relayConnections
        self.relayConnectionsFailed = relayConnectionsFailed
        self.relayConnectionsRatelimited = relayConnectionsRatelimited
    }

    

    
}

#if compiler(>=6)
extension MpNetworkMetrics: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMpNetworkMetrics: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MpNetworkMetrics {
        return
            try MpNetworkMetrics(
                relayConnections: FfiConverterUInt64.read(from: &buf), 
                relayConnectionsFailed: FfiConverterUInt64.read(from: &buf), 
                relayConnectionsRatelimited: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: MpNetworkMetrics, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.relayConnections, into: &buf)
        FfiConverterUInt64.write(value.relayConnectionsFailed, into: &buf)
        FfiConverterUInt64.write(value.relayConnectionsRatelimited, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMpNetworkMetrics_lift(_ buf: RustBuffer) throws -> MpNetworkMetrics {
    return try FfiConverterTypeMpNetworkMetrics.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMpNetworkMetrics_lower(_ value: MpNetworkMetrics) -> RustBuffer {
    return FfiConverterTypeMpNetworkMetrics.lower(value)
}


/**
 * Why a pipe closed, when it has.
 */

public enum MpCloseReason: Equatable, Hashable {
    
    /**
     * Someone called `shutdown`, on this side or the far one.
     */
    case shutdown
    /**
     * The local listener stopped accepting. The pipe is gone for a reason
     * that is this machine's, not the network's.
     */
    case listenerFailed





}

#if compiler(>=6)
extension MpCloseReason: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMpCloseReason: FfiConverterRustBuffer {
    typealias SwiftType = MpCloseReason

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MpCloseReason {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .shutdown
        
        case 2: return .listenerFailed
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: MpCloseReason, into buf: inout [UInt8]) {
        switch value {
        
        
        case .shutdown:
            writeInt(&buf, Int32(1))
        
        
        case .listenerFailed:
            writeInt(&buf, Int32(2))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMpCloseReason_lift(_ buf: RustBuffer) throws -> MpCloseReason {
    return try FfiConverterTypeMpCloseReason.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMpCloseReason_lower(_ value: MpCloseReason) -> RustBuffer {
    return FfiConverterTypeMpCloseReason.lower(value)
}



/**
 * Why a dial did not produce a pipe.
 *
 * Every variant carries a sentence rather than a code, because the app shows
 * it. None of them carries the ticket: a ticket is a bearer credential, and
 * an error rendered into a log or a crash report is exactly where one should
 * not appear.
 */
public 
enum MpError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    /**
     * The ticket is not a ticket: wrong prefix, bad base32, failed checksum,
     * or a length outside the format's bounds.
     *
     * Distinct from every other variant because it is the only one the caller
     * can fix by looking at what they pasted.
     */
    case BadTicket(
        /**
         * What was wrong with it, in a sentence. Never contains the ticket.
         */reason: String
    )
    /**
     * The ticket names a version of the format this build does not implement.
     */
    case UnsupportedTicketVersion(
        /**
         * The version byte the ticket carried.
         */version: UInt8
    )
    /**
     * The local loopback port could not be bound. Nothing to do with the far
     * machine; another process most likely holds it.
     */
    case Bind(
        /**
         * The operating system's reason.
         */reason: String
    )
    /**
     * The endpoint underneath could not start. A local failure again, but of
     * the transport rather than of one socket.
     */
    case Endpoint(
        /**
         * The operating system's reason.
         */reason: String
    )
    /**
     * A relay URL, in the ticket or in the options, is not a URL.
     */
    case InvalidRelay(
        /**
         * The offending value. A relay URL is public infrastructure, not a
         * credential, so this one is safe to render.
         */url: String
    )
    /**
     * The far machine could not be reached at all.
     */
    case PeerUnreachable
    /**
     * Something modelpipe grew that this build does not know about.
     *
     * `ConnectError` is `#[non_exhaustive]`; this is where a new variant
     * lands until someone maps it. Retryable, on the reasoning that an
     * unknown transport failure is more often transient than permanent.
     */
    case Unknown(
        /**
         * The upstream `Debug` rendering, for a bug report.
         */detail: String
    )

    
    /**
     * Whether dialling again could plausibly succeed without anything else
     * changing.
     *
     * The app uses this to decide between offering a retry and telling the
     * person to go fix something. A bad ticket is not retryable however many
     * times it is pasted; a peer that was asleep may not be next time.
     */
public func isRetryable() -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_modelpipe_ffi_fn_method_mperror_is_retryable(
            FfiConverterTypeMpError_lower(self),uniffiCallStatus
    )
})
}
    
    /**
     * The sentence to show a person.
     *
     * Use this, and not Swift's `localizedDescription`. `UniFFI` generates
     * `errorDescription` for every error enum as `String(reflecting: self)`,
     * which is the *debug* rendering of the case and its payload:
     *
     * ```text
     * modelpipe_ffi.MpError.Bind(reason: "Address already in use (os error 48)")
     * ```
     *
     * That compiles, reads as a plausible message, and shows somebody the
     * inside of the binding. This is the [`Display`] impl below — the one
     * written to be read — and the Swift smoke test asserts the difference
     * so it cannot quietly become the other thing.
     *
     * [`Display`]: std::fmt::Display
     */
public func message() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_modelpipe_ffi_fn_method_mperror_message(
            FfiConverterTypeMpError_lower(self),uniffiCallStatus
    )
})
}
    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension MpError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMpError: FfiConverterRustBuffer {
    typealias SwiftType = MpError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MpError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .BadTicket(
            reason: try FfiConverterString.read(from: &buf)
            )
        case 2: return .UnsupportedTicketVersion(
            version: try FfiConverterUInt8.read(from: &buf)
            )
        case 3: return .Bind(
            reason: try FfiConverterString.read(from: &buf)
            )
        case 4: return .Endpoint(
            reason: try FfiConverterString.read(from: &buf)
            )
        case 5: return .InvalidRelay(
            url: try FfiConverterString.read(from: &buf)
            )
        case 6: return .PeerUnreachable
        case 7: return .Unknown(
            detail: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: MpError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .BadTicket(reason):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(reason, into: &buf)
            
        
        case let .UnsupportedTicketVersion(version):
            writeInt(&buf, Int32(2))
            FfiConverterUInt8.write(version, into: &buf)
            
        
        case let .Bind(reason):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(reason, into: &buf)
            
        
        case let .Endpoint(reason):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(reason, into: &buf)
            
        
        case let .InvalidRelay(url):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(url, into: &buf)
            
        
        case .PeerUnreachable:
            writeInt(&buf, Int32(6))
        
        
        case let .Unknown(detail):
            writeInt(&buf, Int32(7))
            FfiConverterString.write(detail, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMpError_lift(_ buf: RustBuffer) throws -> MpError {
    return try FfiConverterTypeMpError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMpError_lower(_ value: MpError) -> RustBuffer {
    return FfiConverterTypeMpError.lower(value)
}


/**
 * What the pipe is doing, in the four states the app already draws.
 *
 * The names and order match `GGChatCore.PipeStatus` exactly, because the
 * consumer maps one to the other and a reordering would be a silent
 * mistranslation rather than a compile error.
 */

public enum MpPipeStatus: Equatable, Hashable {
    
    /**
     * Bound locally, with no path to the far machine yet. Not an error: a
     * pipe dialled at a machine that is switched off sits here.
     */
    case idle
    /**
     * A hole-punched path straight to the far machine.
     */
    case direct
    /**
     * Going through a relay, which carries ciphertext it cannot read.
     */
    case relayed
    /**
     * Terminal. Nothing further will be reported; dial again to recover.
     */
    case closed





}

#if compiler(>=6)
extension MpPipeStatus: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMpPipeStatus: FfiConverterRustBuffer {
    typealias SwiftType = MpPipeStatus

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MpPipeStatus {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .idle
        
        case 2: return .direct
        
        case 3: return .relayed
        
        case 4: return .closed
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: MpPipeStatus, into buf: inout [UInt8]) {
        switch value {
        
        
        case .idle:
            writeInt(&buf, Int32(1))
        
        
        case .direct:
            writeInt(&buf, Int32(2))
        
        
        case .relayed:
            writeInt(&buf, Int32(3))
        
        
        case .closed:
            writeInt(&buf, Int32(4))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMpPipeStatus_lift(_ buf: RustBuffer) throws -> MpPipeStatus {
    return try FfiConverterTypeMpPipeStatus.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMpPipeStatus_lower(_ value: MpPipeStatus) -> RustBuffer {
    return FfiConverterTypeMpPipeStatus.lower(value)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt16: FfiConverterRustBuffer {
    typealias SwiftType = UInt16?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt16.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt16.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeMpCloseReason: FfiConverterRustBuffer {
    typealias SwiftType = MpCloseReason?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeMpCloseReason.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeMpCloseReason.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeMpPipeStatus: FfiConverterRustBuffer {
    typealias SwiftType = MpPipeStatus?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeMpPipeStatus.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeMpPipeStatus.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}
private let UNIFFI_RUST_FUTURE_POLL_READY: Int8 = 0
private let UNIFFI_RUST_FUTURE_POLL_WAKE: Int8 = 1

fileprivate let uniffiContinuationHandleMap = UniffiHandleMap<UnsafeContinuation<Int8, Never>>()

fileprivate func uniffiRustCallAsync<F, T>(
    rustFutureFunc: () -> UInt64,
    pollFunc: (UInt64, @escaping UniffiRustFutureContinuationCallback, UInt64) -> (),
    completeFunc: (UInt64, UnsafeMutablePointer<RustCallStatus>) -> F,
    freeFunc: (UInt64) -> (),
    liftFunc: (F) throws -> T,
    errorHandler: ((RustBuffer) throws -> Swift.Error)?
) async throws -> T {
    // Make sure to call the ensure init function since future creation doesn't have a
    // RustCallStatus param, so doesn't use makeRustCall()
    uniffiEnsureModelpipeFfiInitialized()
    let rustFuture = rustFutureFunc()
    defer {
        freeFunc(rustFuture)
    }
    var pollResult: Int8;
    repeat {
        pollResult = await withUnsafeContinuation {
            pollFunc(
                rustFuture,
                { handle, pollResult in
                    uniffiFutureContinuationCallback(handle: handle, pollResult: pollResult)
                },
                uniffiContinuationHandleMap.insert(obj: $0)
            )
        }
    } while pollResult != UNIFFI_RUST_FUTURE_POLL_READY

    return try liftFunc(makeRustCall(
        { completeFunc(rustFuture, $0) },
        errorHandler: errorHandler
    ))
}

// Callback handlers for an async calls.  These are invoked by Rust when the future is ready.  They
// lift the return value or error and resume the suspended function.
fileprivate func uniffiFutureContinuationCallback(handle: UInt64, pollResult: Int8) {
    if let continuation = try? uniffiContinuationHandleMap.remove(handle: handle) {
        continuation.resume(returning: pollResult)
    } else {
        print("uniffiFutureContinuationCallback invalid handle")
    }
}
/**
 * Dial the machine a pairing ticket names.
 *
 * Returns **as soon as the local port is bound**, not once the far machine
 * answers. That is upstream's contract and it is the one the app is built
 * around: the returned pipe starts at [`MpPipeStatus::Idle`] and walks to
 * `Relayed` or `Direct` afterwards, which is what the status pill shows. A
 * machine that is switched off produces a perfectly good pipe that stays
 * `Idle` — it is not an error, and treating it as one would mean a dial that
 * blocks for the thirty seconds iroh spends giving up.
 *
 * Takes no token, because there is nothing to take: see [`MpConnectOptions`].
 *
 * # Errors
 *
 * [`MpError::BadTicket`] or [`MpError::UnsupportedTicketVersion`] if the
 * pairing string is not one, before anything touches the network; then
 * whatever the dial itself refuses with.
 */
public func mpConnect(ticket: String, options: MpConnectOptions)async throws  -> MpPipe  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_modelpipe_ffi_fn_func_mp_connect(FfiConverterString.lower(ticket),FfiConverterTypeMpConnectOptions_lower(options)
                )
            },
            pollFunc: ffi_modelpipe_ffi_rust_future_poll_u64,
            completeFunc: ffi_modelpipe_ffi_rust_future_complete_u64,
            freeFunc: ffi_modelpipe_ffi_rust_future_free_u64,
            liftFunc: FfiConverterTypeMpPipe_lift,
            errorHandler: FfiConverterTypeMpError_lift
        )
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_modelpipe_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_modelpipe_ffi_checksum_func_mp_connect() != 4759) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_modelpipe_ffi_checksum_method_mppipe_base_url() != 22399) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_modelpipe_ffi_checksum_method_mppipe_close_reason() != 54952) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_modelpipe_ffi_checksum_method_mppipe_network_metrics() != 40607) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_modelpipe_ffi_checksum_method_mppipe_notify_network_change() != 51570) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_modelpipe_ffi_checksum_method_mppipe_port() != 13940) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_modelpipe_ffi_checksum_method_mppipe_shutdown() != 38799) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_modelpipe_ffi_checksum_method_mppipe_status() != 13864) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_modelpipe_ffi_checksum_method_mppipe_status_changed_since() != 31817) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureModelpipeFfiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all